### ISSUE TITLE
Project lifecycle/proposal process

### ISSUE THREAD

**Issue by caniszczyk** [ucfoundation/tac#3]

**Comment by sarob** [comment]
To better understand, I am using Kepler.gl as a reference, since Uber plans on contributing the project to UCF. Can I assume that Kepler.gl is at the growth stage? The project has been an active open source project over some time. Do you think some projects like Kepler.gl could start at the impact stage?

**Comment by bhenhsi** [comment]
Project lifecycle has been merged.
